### ISSUE TITLE
Комментарии 05.02.2015

### ISSUE THREAD

**Issue by newsrussia** [srgg6701/Moscow-Home#1]
1. По выпадающему меню "Услуги"  "Контакты" я вчера направил комментарии, пока не исправлено. 
   2.В меню "Консультация" должна быть кнопка "Прикрепить файл". 
   3.На главной странице крайняя галочка справа - там другой текст. 
   4.Строительство элитной недвижимости с 2000 года. 5. Телефоны (495) 762-99-66.

**Comment by newsrussia** [comment]
В целом внутренние страницы Ок. Соответствуют дизайну.
Ошибки на 10.02.2015.
1.Выпадающее меню не убирается.
2.При нажатии на кнопки "подрбнее" внутри меню выделяется синяя рамка. Ее нужно убрать.
3."Стоимость услуг" внизу внутренних страниц сейчас делаем неактивными, но предусматриваем возможность по ссылке скачать файл.
4."Проектирование зданий и помещений" - фоновая картинка в шапке заходит на текст. Нужно или ее меньше сделать или задвинуть наполовину за край, влево (главное чтобы текст оказывался не на ней).
5.Проектирование дизайна интерьера я так понимаю в работе.
6.Меню "Перезвоните мне" должно быть активно. Возможен дубляж меню "Консультация"
7.Верхняя строка "О компании, услуги, контакты..." - должна быть на всех внутренних страницах.

**Comment by srgg6701** [comment]
"7.Верхняя строка "О компании, услуги, контакты..." - должна быть на всех внутренних страницах."
- А ПОЧЕМУ ЭТА СТРОКА НЕ НА ВСЕХ МАКЕТАХ?!!!

**Comment by srgg6701** [comment]
◄►
