### ISSUE TITLE
Присоединение файла

### ISSUE THREAD

**Issue by newsrussia** [srgg6701/Moscow-Home#10]
Присоединяя файл в форме обратная связь, видишь еще одну кнопку за ним.

**Comment by srgg6701** [comment]
Скриншот дайте плз.

8 марта 2015 г., 20:05 пользователь Slava notifications@github.com
написал:

> Присоединяя файл в форме обратная связь, видишь еще одну кнопку за ним.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/10.

## 

SY Sergey V. Cleftsow

**Comment by newsrussia** [comment]
Эта ошибка в разных браузерах видна.

С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

Воскресенье, 08 марта 2015, 10:07 -07:00 от Сергей notifications@github.com:

**Comment by srgg6701** [comment]
Я это модифицировал. Но вы должны учитывать, что оно в разных браузерах будет выглядеть по-разному и этот элемент вообще никакой стилизации не поддаётся, т.е., его можно только двигать, изменять размеры и видимость.

**Comment by newsrussia** [comment]
Кнопка позади видна как и прежде.
возможно убрать ее визуал? Пусть хотя бы текст торчит, но не серый фон.

С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

Понедельник, 09 марта 2015, 9:47 -07:00 от Сергей notifications@github.com:

**Comment by srgg6701** [comment]
Под каким браузером "торчит"? У меня не торичит, нужно отловить момент.

9 марта 2015 г., 20:28 пользователь Slava notifications@github.com
написал:

> Кнопка позади видна как и прежде.
> возможно убрать ее визуал? Пусть хотя бы текст торчит, но не серый фон.
> 
> С уважением,
> Вячеслав Иванов
> тел.: 8 (916) 360-47-88
> e-mail: newsrussia@list.ru
> 
> Понедельник, 09 марта 2015, 9:47 -07:00 от Сергей <
> notifications@github.com>:
> 
> > Я это модифицировал. Но вы должны учитывать, что оно в разных браузерах
> > будет выглядеть по-разному и этот элемент вообще никакой стилизации не
> > поддаётся, т.е., его можно только двигать, изменять размеры и видимость.
> > 
> > —
> > Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-77901173.

## 

SY Sergey V. Cleftsow

**Comment by newsrussia** [comment]
Гугл хром.
С разных компьютеров.

С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

Понедельник, 09 марта 2015, 15:01 -07:00 от Сергей notifications@github.com:

**Comment by srgg6701** [comment]
Вы можете скриншот прислать?

10 марта 2015 г., 10:03 пользователь Slava notifications@github.com
написал:

> Гугл хром.
> С разных компьютеров.
> 
> С уважением,
> Вячеслав Иванов
> тел.: 8 (916) 360-47-88
> e-mail: newsrussia@list.ru
> 
> Понедельник, 09 марта 2015, 15:01 -07:00 от Сергей <
> notifications@github.com>:
> 
> > Под каким браузером "торчит"? У меня не торичит, нужно отловить момент.
> > 
> > 9 марта 2015 г., 20:28 пользователь Slava notifications@github.com
> > написал:
> > 
> > > Кнопка позади видна как и прежде.
> > > возможно убрать ее визуал? Пусть хотя бы текст торчит, но не серый фон.
> > > 
> > > С уважением,
> > > Вячеслав Иванов
> > > тел.: 8 (916) 360-47-88
> > > e-mail: newsrussia@list.ru
> > > 
> > > Понедельник, 09 марта 2015, 9:47 -07:00 от Сергей <
> > > notifications@github.com>:
> > > 
> > > > Я это модифицировал. Но вы должны учитывать, что оно в разных браузерах
> > > > будет выглядеть по-разному и этот элемент вообще никакой стилизации не
> > > > поддаётся, т.е., его можно только двигать, изменять размеры и видимость.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-77901173>.
> > 
> > ## 
> > 
> > SY Sergey V. Cleftsow
> > —
> > Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78005005.

## 

SY Sergey V. Cleftsow

**Comment by newsrussia** [comment]
Уже отправлял.

Ничего не изменилось.
Выглядит также.

С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

Вторник, 10 марта 2015, 1:31 -07:00 от Сергей notifications@github.com:

**Comment by srgg6701** [comment]
Решета в чудесе.
Но в реальной жизни, конечно, всё бывает. Сделал по-железо-бетонному
теперь. Проверяйте плз.
И подтвердите пожалуйста, что дата завершения работ по разработке мобильной
версии ─ 20.03 с.г.

10 марта 2015 г., 11:45 пользователь Slava notifications@github.com
написал:

> Уже отправлял.
> 
> Ничего не изменилось.
> Выглядит также.
> 
> С уважением,
> Вячеслав Иванов
> тел.: 8 (916) 360-47-88
> e-mail: newsrussia@list.ru
> 
> Вторник, 10 марта 2015, 1:31 -07:00 от Сергей notifications@github.com:
> 
> > Вы можете скриншот прислать?
> > 
> > 10 марта 2015 г., 10:03 пользователь Slava notifications@github.com
> > написал:
> > 
> > > Гугл хром.
> > > С разных компьютеров.
> > > 
> > > С уважением,
> > > Вячеслав Иванов
> > > тел.: 8 (916) 360-47-88
> > > e-mail: newsrussia@list.ru
> > > 
> > > Понедельник, 09 марта 2015, 15:01 -07:00 от Сергей <
> > > notifications@github.com>:
> > > 
> > > > Под каким браузером "торчит"? У меня не торичит, нужно отловить момент.
> > > > 
> > > > 9 марта 2015 г., 20:28 пользователь Slava notifications@github.com
> > > > написал:
> > > > 
> > > > > Кнопка позади видна как и прежде.
> > > > > возможно убрать ее визуал? Пусть хотя бы текст торчит, но не серый
> > > > > фон.
> > > > > 
> > > > > С уважением,
> > > > > Вячеслав Иванов
> > > > > тел.: 8 (916) 360-47-88
> > > > > e-mail: newsrussia@list.ru
> > > > > 
> > > > > Понедельник, 09 марта 2015, 9:47 -07:00 от Сергей <
> > > > > notifications@github.com>:
> > > > > 
> > > > > > Я это модифицировал. Но вы должны учитывать, что оно в разных
> > > > > > браузерах
> > > > > > будет выглядеть по-разному и этот элемент вообще никакой стилизации
> > > > > > не
> > > > > > поддаётся, т.е., его можно только двигать, изменять размеры и
> > > > > > видимость.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-77901173
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > SY Sergey V. Cleftsow
> > > > —
> > > > Reply to this email directly or view it on GitHub .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78005005>.
> > 
> > ## 
> > 
> > SY Sergey V. Cleftsow
> > —
> > Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78014573.

## 

SY Sergey V. Cleftsow

**Comment by newsrussia** [comment]
1.Кнопка больше не видна. Спасибо.
2.Дату мобильной версии подтверждаю.
3.Поменяйте пожалуйста надпись на главной странице: " Строительство  элитной недвижимости с 2000 года" на - " загородной "
 

С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

Вторник, 10 марта 2015, 2:52 -07:00 от Сергей notifications@github.com:

**Comment by srgg6701** [comment]
Заменил.
Это находится в модуле _Footer_
Расширения → Менеджер модулей → Footer

10 марта 2015 г., 13:09 пользователь Slava notifications@github.com
написал:

> 1.Кнопка больше не видна. Спасибо.
> 2.Дату мобильной версии подтверждаю.
> 3.Поменяйте пожалуйста надпись на главной странице: " Строительство
> элитной недвижимости с 2000 года" на - " загородной "
> 
> С уважением,
> Вячеслав Иванов
> тел.: 8 (916) 360-47-88
> e-mail: newsrussia@list.ru
> 
> Вторник, 10 марта 2015, 2:52 -07:00 от Сергей notifications@github.com:
> 
> > Решета в чудесе.
> > Но в реальной жизни, конечно, всё бывает. Сделал по-железо-бетонному
> > теперь. Проверяйте плз.
> > И подтвердите пожалуйста, что дата завершения работ по разработке
> > мобильной
> > версии ─ 20.03 с.г.
> > 
> > 10 марта 2015 г., 11:45 пользователь Slava notifications@github.com
> > написал:
> > 
> > > Уже отправлял.
> > > 
> > > Ничего не изменилось.
> > > Выглядит также.
> > > 
> > > С уважением,
> > > Вячеслав Иванов
> > > тел.: 8 (916) 360-47-88
> > > e-mail: newsrussia@list.ru
> > > 
> > > Вторник, 10 марта 2015, 1:31 -07:00 от Сергей <notifications@github.com
> > > :
> > > 
> > > > Вы можете скриншот прислать?
> > > > 
> > > > 10 марта 2015 г., 10:03 пользователь Slava notifications@github.com
> > > > написал:
> > > > 
> > > > > Гугл хром.
> > > > > С разных компьютеров.
> > > > > 
> > > > > С уважением,
> > > > > Вячеслав Иванов
> > > > > тел.: 8 (916) 360-47-88
> > > > > e-mail: newsrussia@list.ru
> > > > > 
> > > > > Понедельник, 09 марта 2015, 15:01 -07:00 от Сергей <
> > > > > notifications@github.com>:
> > > > > 
> > > > > > Под каким браузером "торчит"? У меня не торичит, нужно отловить
> > > > > > момент.
> > > > > > 
> > > > > > 9 марта 2015 г., 20:28 пользователь Slava <notifications@github.com
> > > > > > 
> > > > > > написал:
> > > > > > 
> > > > > > > Кнопка позади видна как и прежде.
> > > > > > > возможно убрать ее визуал? Пусть хотя бы текст торчит, но не серый
> > > > > > > фон.
> > > > > > > 
> > > > > > > С уважением,
> > > > > > > Вячеслав Иванов
> > > > > > > тел.: 8 (916) 360-47-88
> > > > > > > e-mail: newsrussia@list.ru
> > > > > > > 
> > > > > > > Понедельник, 09 марта 2015, 9:47 -07:00 от Сергей <
> > > > > > > notifications@github.com>:
> > > > > > > 
> > > > > > > > Я это модифицировал. Но вы должны учитывать, что оно в разных
> > > > > > > > браузерах
> > > > > > > > будет выглядеть по-разному и этот элемент вообще никакой
> > > > > > > > стилизации
> > > > > > > > не
> > > > > > > > поддаётся, т.е., его можно только двигать, изменять размеры и
> > > > > > > > видимость.
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub .
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > > 
> > > > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-77901173
> > > > > .
> > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > SY Sergey V. Cleftsow
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78005005
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > SY Sergey V. Cleftsow
> > > > —
> > > > Reply to this email directly or view it on GitHub .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78014573>.
> > 
> > ## 
> > 
> > SY Sergey V. Cleftsow
> > —
> > Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78025732.

## 

SY Sergey V. Cleftsow

**Comment by newsrussia** [comment]
Надпись уехала....

С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

Вторник, 10 марта 2015, 3:31 -07:00 от Сергей notifications@github.com:

**Comment by srgg6701** [comment]
Не везёт©
А сейчас как? Нормально?

10 марта 2015 г., 13:36 пользователь Slava notifications@github.com
написал:

> Надпись уехала....
> 
> С уважением,
> Вячеслав Иванов
> тел.: 8 (916) 360-47-88
> e-mail: newsrussia@list.ru
> 
> Вторник, 10 марта 2015, 3:31 -07:00 от Сергей notifications@github.com:
> 
> > Заменил.
> > Это находится в модуле _Footer_
> > 
> > Расширения → Менеджер модулей → Footer
> > 
> > 10 марта 2015 г., 13:09 пользователь Slava notifications@github.com
> > написал:
> > 
> > > 1.Кнопка больше не видна. Спасибо.
> > > 2.Дату мобильной версии подтверждаю.
> > > 3.Поменяйте пожалуйста надпись на главной странице: " Строительство
> > > элитной недвижимости с 2000 года" на - " загородной "
> > > 
> > > С уважением,
> > > Вячеслав Иванов
> > > тел.: 8 (916) 360-47-88
> > > e-mail: newsrussia@list.ru
> > > 
> > > Вторник, 10 марта 2015, 2:52 -07:00 от Сергей <notifications@github.com
> > > :
> > > 
> > > > Решета в чудесе.
> > > > Но в реальной жизни, конечно, всё бывает. Сделал по-железо-бетонному
> > > > теперь. Проверяйте плз.
> > > > И подтвердите пожалуйста, что дата завершения работ по разработке
> > > > мобильной
> > > > версии ─ 20.03 с.г.
> > > > 
> > > > 10 марта 2015 г., 11:45 пользователь Slava notifications@github.com
> > > > написал:
> > > > 
> > > > > Уже отправлял.
> > > > > 
> > > > > Ничего не изменилось.
> > > > > Выглядит также.
> > > > > 
> > > > > С уважением,
> > > > > Вячеслав Иванов
> > > > > тел.: 8 (916) 360-47-88
> > > > > e-mail: newsrussia@list.ru
> > > > > 
> > > > > Вторник, 10 марта 2015, 1:31 -07:00 от Сергей <
> > > > > notifications@github.com
> > > > > :
> > > > > 
> > > > > > Вы можете скриншот прислать?
> > > > > > 
> > > > > > 10 марта 2015 г., 10:03 пользователь Slava <
> > > > > > notifications@github.com>
> > > > > > написал:
> > > > > > 
> > > > > > > Гугл хром.
> > > > > > > С разных компьютеров.
> > > > > > > 
> > > > > > > С уважением,
> > > > > > > Вячеслав Иванов
> > > > > > > тел.: 8 (916) 360-47-88
> > > > > > > e-mail: newsrussia@list.ru
> > > > > > > 
> > > > > > > Понедельник, 09 марта 2015, 15:01 -07:00 от Сергей <
> > > > > > > notifications@github.com>:
> > > > > > > 
> > > > > > > > Под каким браузером "торчит"? У меня не торичит, нужно отловить
> > > > > > > > момент.
> > > > > > > > 
> > > > > > > > 9 марта 2015 г., 20:28 пользователь Slava <
> > > > > > > > notifications@github.com
> > > > > > > > 
> > > > > > > > написал:
> > > > > > > > 
> > > > > > > > > Кнопка позади видна как и прежде.
> > > > > > > > > возможно убрать ее визуал? Пусть хотя бы текст торчит, но не
> > > > > > > > > серый
> > > > > > > > > фон.
> > > > > > > > > 
> > > > > > > > > С уважением,
> > > > > > > > > Вячеслав Иванов
> > > > > > > > > тел.: 8 (916) 360-47-88
> > > > > > > > > e-mail: newsrussia@list.ru
> > > > > > > > > 
> > > > > > > > > Понедельник, 09 марта 2015, 9:47 -07:00 от Сергей <
> > > > > > > > > notifications@github.com>:
> > > > > > > > > 
> > > > > > > > > > Я это модифицировал. Но вы должны учитывать, что оно в разных
> > > > > > > > > > браузерах
> > > > > > > > > > будет выглядеть по-разному и этот элемент вообще никакой
> > > > > > > > > > стилизации
> > > > > > > > > > не
> > > > > > > > > > поддаётся, т.е., его можно только двигать, изменять размеры и
> > > > > > > > > > видимость.
> > > > > > > > > > 
> > > > > > > > > > —
> > > > > > > > > > Reply to this email directly or view it on GitHub .
> > > > > > > > > 
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > <
> > > > > > > 
> > > > > > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-77901173
> > > > > > > .
> > > > > > > 
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > SY Sergey V. Cleftsow
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub .
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > > 
> > > > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78005005
> > > > > .
> > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > SY Sergey V. Cleftsow
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78014573
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > SY Sergey V. Cleftsow
> > > > —
> > > > Reply to this email directly or view it on GitHub .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78025732>.
> > 
> > ## 
> > 
> > SY Sergey V. Cleftsow
> > —
> > Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78029540.

## 

SY Sergey V. Cleftsow

**Comment by newsrussia** [comment]
Да, ок.

С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

Вторник, 10 марта 2015, 3:40 -07:00 от Сергей notifications@github.com:

**Comment by newsrussia** [comment]
Сергей, чет у нас постоянно картинки слетают в галерее.
Снова в Опере беда.

Хочу отметить, что с моей стороны совершенно никаких действий на сайте нет.

С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

**Comment by srgg6701** [comment]
Давайте, если сейчас, на этой стадии работ, у вас что-то внезапно "слетит",
сообщайте мне в скайпе сразу.
Я ничего слетевшего в Опере не вижу, пришлите скриншот плз., если вы видите.

10 марта 2015 г., 15:58 пользователь Slava notifications@github.com
написал:

> Сергей, чет у нас постоянно картинки слетают в галерее.
> Снова в Опере беда.
> 
> Хочу отметить, что с моей стороны совершенно никаких действий на сайте нет.
> 
> С уважением,
> Вячеслав Иванов
> тел.: 8 (916) 360-47-88
> e-mail: newsrussia@list.ru
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78047628.

## 

SY Sergey V. Cleftsow

**Comment by srgg6701** [comment]
Проверьте отображение сайта при высоте рабочей части экрана не более 768px
пожалуйста (это пока не мобильная версия, макет адаптируется при ширине не
менее 1024px).

11 марта 2015 г., 1:44 пользователь Sergey Cleftsow srgg67@gmail.com
написал:

> Давайте, если сейчас, на этой стадии работ, у вас что-то внезапно
> "слетит", сообщайте мне в скайпе сразу.
> Я ничего слетевшего в Опере не вижу, пришлите скриншот плз., если вы
> видите.
> 
> 10 марта 2015 г., 15:58 пользователь Slava notifications@github.com
> написал:
> 
> Сергей, чет у нас постоянно картинки слетают в галерее.
> 
> > Снова в Опере беда.
> > 
> > Хочу отметить, что с моей стороны совершенно никаких действий на сайте
> > нет.
> > 
> > С уважением,
> > Вячеслав Иванов
> > тел.: 8 (916) 360-47-88
> > e-mail: newsrussia@list.ru
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78047628
> > .
> 
> ## 
> 
> SY Sergey V. Cleftsow

## 

SY Sergey V. Cleftsow

**Comment by newsrussia** [comment]
## Проверил на мобильном. Вижу сайт меньшего формата. Кнопки лево право уехали наверх. Выпадающее меню недоступно так как кроется за строкой браузера поиск.

Отправлено из мобильной Почты Mail.Ru
среда, 11 марта 2015г., 14:55 +0300 от Сергей notifications@github.com:

**Comment by srgg6701** [comment]
Сейчас речь идёт не о мобильной версии (я на этом делал акцент), а о
десктопной (т.е., шириной экрана не менее 1024px) но с малой высотой (768px
и меньше).
У меня при этих условиях всё показывает нормально. Если у вас нет, пришлите
скриншот или на экране покажите.

11 марта 2015 г., 19:14 пользователь Slava notifications@github.com
написал:

> Проверил на мобильном. Вижу сайт меньшего формата. Кнопки лево право
> уехали наверх. Выпадающее меню недоступно так как кроется за строкой
> 
> ## браузера поиск.
> 
> Отправлено из мобильной Почты Mail.Ru
> среда, 11 марта 2015г., 14:55 +0300 от Сергей notifications@github.com:
> 
> > Проверьте отображение сайта при высоте рабочей части экрана не более 768px
> > пожалуйста (это пока не мобильная версия, макет адаптируется при ширине не
> > менее 1024px).
> > 11 марта 2015 г., 1:44 пользователь Sergey Cleftsow srgg67@gmail.com
> > написал:
> > 
> > > Давайте, если сейчас, на этой стадии работ, у вас что-то внезапно
> > > "слетит", сообщайте мне в скайпе сразу.
> > > Я ничего слетевшего в Опере не вижу, пришлите скриншот плз., если вы
> > > видите.
> > > 
> > > 10 марта 2015 г., 15:58 пользователь Slava notifications@github.com
> > > написал:
> > > 
> > > Сергей, чет у нас постоянно картинки слетают в галерее.
> > > 
> > > > Снова в Опере беда.
> > > > 
> > > > Хочу отметить, что с моей стороны совершенно никаких действий на сайте
> > > > нет.
> > > > 
> > > > С уважением,
> > > > Вячеслав Иванов
> > > > тел.: 8 (916) 360-47-88
> > > > e-mail: newsrussia@list.ru
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78047628>
> > > > .
> > > 
> > > ## 
> > > 
> > > SY Sergey V. Cleftsow
> > > 
> > > ## 
> > > 
> > > SY Sergey V. Cleftsow
> > > —
> > > Reply to this email directly or  view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/10#issuecomment-78296233.

## 

SY Sergey V. Cleftsow
