### ISSUE TITLE
Техзадание 22 мая 2015

### ISSUE THREAD

**Issue by newsrussia** [srgg6701/Moscow-Home#15]
А) Сайт для мониторов
ДОРАБОТКА
1. Телефон вверху главной страницы нужно сделать не картинкой, а текстом (чтобы в мобильной версии сайта по нему могли звонить).
2. В разделе «Контакты» нужно переставить «маячок» на карте по адресу: 11 км Рублёво-Успенского шоссе, д.Усово, НПИЗ "Счастливый дом", д.1 
На карте Яндекса это ссылка: https://maps.yandex.ru/-/CVS2YZny. 
Название маячка «Дома класса люкс. Мы тут!» - меняем на «Компания  Moscow Home».
3. Круглые кнопки сделать не черными, а более прозрачными (темно-серые прозрачные статичные и светло-серые прозрачные при перелистывании).
4. Немного уменьшить красную плашку на главной странице по высоте и сделать более прозрачной.
ДОПРАБОТЫ
5.Для раздела «Наши работы»- нужна дополнительная строчка с фото для галерей (желтая полоса под каждой красной полосой). При клике на фото в желтой полосе должно меняться главное крупное фото.
6. На странице "Галерея" под каждый дом нужен блок с выпадающим с описанием проекта (Аналог "Подробнее" на остальных страницах). В котором нужна только текстовая информация.

Б) Сайт для мобильных
ДОРАБОТКА
1. Круглые кнопки на главной странице (в мобильной версии) нужно сделать меньше в 2 раза.
2. Кнопка «Перезвоните мне» не работает.
3. Кнопки листания маленьких картинок не работают.
ДОПРАБОТЫ
4. Нужен телефон на главной странице. (Вставка красной плашки с телефоном внизу страницы?) – образец прилагается.
5. Нужна надпись «консультация» на кнопке справа. (Либо поменять значок трубки «24 часа» на знак вопроса – для мобильной версии?) – образец прилагается.

В) Управление сайтом
Нужно меню для замены текстов, которое бы не нарушало программный код сайта.

**Comment by serge-serg** [comment]
Доработал.
