### ISSUE TITLE
Ссылки на соцсети

### ISSUE THREAD

**Issue by newsrussia** [srgg6701/Moscow-Home#2]
Сергей, прошу добавить на сайт ссылки в соцсети:
http://vk.com/moscowhomeru
https://www.facebook.com/moscowhome
http://ok.ru/group/53402607354098

**Comment by srgg6701** [comment]
1. Мне нужно срочно разобраться с вашими присланными картинками, что
   является актуальной версией, что устаревшей ─ вы прислали мне кучу
   отличающихся друг от друга картинок.
   До этого момента не имеет смысла довёрстывать раздел "Кровельные и фасадные
   работы".
2. Именно поэтому я _несколько раз_ просил _ничего мне не присылать и не
   перепосылать_ до того момента, пока не будет утверждена вёрстка очередной
   страницы
3. Здесь: https://github.com/srgg6701/Moscow-Home/issues/1
   есть такой пункт:

> 7.Верхняя строка "О компании, услуги, контакты..." - должна быть на всех
> внутренних страницах.

Я уже сверстал основные страницы в соответствии с теми исходниками, которые
был доступны мне по сслыке, которую вы давали. Там это строка не на всех.
Соответственно, перевёрстка потребует дополнительного времени и оплаты.

11 февраля 2015 г., 10:48 пользователь Slava notifications@github.com
написал:

> Сергей, прошу добавить на сайт ссылки в соцсети:
> http://vk.com/moscowhomeru
> https://www.facebook.com/moscowhome
> http://ok.ru/group/53402607354098
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/2.

## 

SY Sergey V. Cleftsow

**Comment by newsrussia** [comment]
Сергей, не понимаю о чем сейчас идет речь.
Вы изъявили желание действовать поэтапно, постранично. На попытки обсудить проект в целом отреагировали достаточно резко (смотрите переписку в скайпе).
Мы обсудили неделю назад главную страницу, перешли к внутренним, сейчас вы говорите что вас "закидали" файлами.
О каком закидывании вы говорите если действуете поэтапно? Финальные файлы Антон передал до начала работ над внутренними страницами...

Необходимость сохранения верхнего меню по сайту мы обсуждали устно, еще месяц назад. Подразумевается что оно должно быть "по умолчанию", поэтому оплачивать его как отдельный элемент мы не сможем..
Если вы не зафиксировали эту потребность после обсуждения (или не захотели фиксировать, полагаясь на свою логику выполнения работ) - это сугубо ваша ошибка.

Прошу вас найти возможность введения этого элемента на всех внутренних страницах, без "переверстки".
С уважением, 
Вячеслав Иванов
тел.: 8 (916) 360-47-88 
e-mail: newsrussia@list.ru

Пятница, 13 февраля 2015, 7:26 -08:00 от Сергей notifications@github.com:

**Comment by srgg6701** [comment]
Д.день.
Думаю, нет смысла разбираться, "кто виноват", вероятно, у меня несколько
другие представления о стандартах разработки. Ситуация, при которой в
процессе работы постоянно меняется дизайн, плюс не на всех макетах
присутствуют все необходимые элементы (не говоря уже о куче других деталей,
о которых я вас даже не информирую), для меня выглядит как полный нонсенс.
Ну да ладно, работа, в любом случае, должна быть выполнена.
Насчёт меню, что оно должно быть на каждой странице, ─ допускаю, что вы это
говорили, но я упустил из виду. Т.о., будет добавлено бесплатно.
Самое главное, что нуждается в срочном уточнении:
1. Какой из вариантов для раздела "Кровельные и фасадные работы" является
актуальным (см. аттачмент)?
2. Пожалуйста, проверьте текущие страницы и сообщите, те ли версии дизайна
реализованы? Я говорю именно о версиях, не о возможных мелких
несоответствиях (это будет устранено в процессе доработки).
По поводу "неубирающегося" меню. Оно реализовано в тестовом режиме,
преднамеренно в таком виде пока. Чтобы его убрать, протсто щёлкните по его
ссылке.

13 февраля 2015 г., 22:33 пользователь Slava notifications@github.com
написал:

> Сергей, не понимаю о чем сейчас идет речь.
> Вы изъявили желание действовать поэтапно, постранично. На попытки обсудить
> проект в целом отреагировали достаточно резко (смотрите переписку в скайпе).
> Мы обсудили неделю назад главную страницу, перешли к внутренним, сейчас вы
> говорите что вас "закидали" файлами.
> О каком закидывании вы говорите если действуете поэтапно? Финальные файлы
> Антон передал до начала работ над внутренними страницами...
> 
> Необходимость сохранения верхнего меню по сайту мы обсуждали устно, еще
> месяц назад. Подразумевается что оно должно быть "по умолчанию", поэтому
> оплачивать его как отдельный элемент мы не сможем..
> Если вы не зафиксировали эту потребность после обсуждения (или не захотели
> фиксировать, полагаясь на свою логику выполнения работ) - это сугубо ваша
> ошибка.
> 
> Прошу вас найти возможность введения этого элемента на всех внутренних
> страницах, без "переверстки".
> С уважением,
> Вячеслав Иванов
> тел.: 8 (916) 360-47-88
> e-mail: newsrussia@list.ru
> 
> Пятница, 13 февраля 2015, 7:26 -08:00 от Сергей <notifications@github.com
> 
> > :
> > 1. Мне нужно срочно разобраться с вашими присланными картинками, что
> > является актуальной версией, что устаревшей ─ вы прислали мне кучу
> > отличающихся друг от друга картинок.
> > До этого момента не имеет смысла довёрстывать раздел "Кровельные и
> > фасадные
> > работы".
> > 2. Именно поэтому я _несколько раз_ просил _ничего мне не присылать и не
> > перепосылать_ до того момента, пока не будет утверждена вёрстка очередной
> > страницы
> > 3. Здесь: https://github.com/srgg6701/Moscow-Home/issues/1
> > есть такой пункт:
> > 
> > > 7.Верхняя строка "О компании, услуги, контакты..." - должна быть на всех
> > > внутренних страницах.
> > 
> > Я уже сверстал основные страницы в соответствии с теми исходниками,
> > которые
> > был доступны мне по сслыке, которую вы давали. Там это строка не на всех.
> > Соответственно, перевёрстка потребует дополнительного времени и оплаты.
> > 
> > 11 февраля 2015 г., 10:48 пользователь Slava notifications@github.com
> > написал:
> > 
> > > Сергей, прошу добавить на сайт ссылки в соцсети:
> > > http://vk.com/moscowhomeru
> > > https://www.facebook.com/moscowhome
> > > http://ok.ru/group/53402607354098
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/srgg6701/Moscow-Home/issues/2.
> > 
> > ## 
> > 
> > SY Sergey V. Cleftsow
> > —
> > Reply to this email directly or view it on GitHub .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srgg6701/Moscow-Home/issues/2#issuecomment-74312368.

## 

SY Sergey V. Cleftsow
