### ISSUE TITLE
Летающие элементы

### ISSUE THREAD

**Issue by newsrussia** [srgg6701/Moscow-Home#4]
Инженерные системы
карандаш
разводной ключ
труба
кабель

Проектирование зданий и помещений
уровень
чертеж
линейка

Дизайн интерьера
диван
рамка
торшер

Общестроительные работы
каска
кирпич
мастерок
кисточка

Кровельные работы
банка краски
ролик
кусок шифера
кусок плитки

**Comment by srgg6701** [comment]
Всунуты куда надо
