### ISSUE TITLE
Правки в сайт

### ISSUE THREAD

**Issue by newsrussia** [srgg6701/Moscow-Home#5]
Общее резюме - плагин Фотогалерей не понравился. Он портит внешний вид.
Всплывающие фото не кадрируются под рамку, а меняют размер, их нужно ловить по всму экрану, чтобы переключить.
Предлагаю заменить этот плагин. Возможно даже на платный, главное чтобы подходил нам по дизайну и был удобен..
1.Все фотогалереи, где внизу идет нумерация - выглядят нехорошо. Нужно ставить только кнопки скроллинга (без бегунка прокрутки).
2.Фотогалерея в "ОБЩЕСТРОИТЕЛЬНЫЕ" не работает.
3.Фотогалерея "КРОВЕЛЬНЫЕ" - в мини-галереях справа и слева по 2 кнопки скроллинга. Они находят друг на друга.
4.Функцию сохранения фото нужно везде отключить.
5.ФАСАДНЫЕ РАБОТЫ - вспомогательные элементы перестали летать по странице.
6.Фотогалерея "ОТОПЛЕНИЕ": при увеличенном фото скроллинг по фото ижет только вправо, влево не идет.

**Comment by newsrussia** [comment]
Дополнение: 
На странице "ДИЗАЙН" - нет вставки кода на сайт с работами партнера.

**Comment by srgg6701** [comment]
Почекано
